version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    env_file: .env.db
    environment:
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: .env.pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge
